version: 2.1
jobs:
  return-true:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "return true"
          command: "true"
workflows:
  say-hello-workflow:
    jobs:
      - return-true
